### ISSUE TITLE
Changes needed for better communication with Kitty API

### ISSUE THREAD

**Issue by therealssj** [kittycash/teller#3]
- [x] Use universal kitty struct [specified here](https://github.com/kittycash/wallet/blob/eed7d1c17d73ebc667cb4c543db5dc45da25a3ef/src/iko/kitty.go#L16)
- [x] Refactor reservation mechanism as required based on above changes
- [x] Test integration after kitty api bug fix.

Timeframe: Before 5/04

**Comment by therealssj** [comment]
Done.
Waiting for integration and bug fixing before closing.

**Comment by briancaine** [comment]
I'm assuming this is part of the IKO, right?

Also, integration / bug fixing where? Is there an issue for it?

**Comment by therealssj** [comment]
Yes Iko.
It is part of this issue only.

**Comment by briancaine** [comment]
How long will the integration / bug fixing take? Is it waiting on anything?

**Comment by therealssj** [comment]
I am on the last stage right now. I fixed most of the bugs today. Now I am waiting on a response from evan on this issue https://github.com/kittycash/kitty-api/issues/32

**Comment by therealssj** [comment]
fixed: https://github.com/kittycash/teller/pull/1
