### ISSUE TITLE
Create skyd to test skycoin deposits

### ISSUE THREAD

**Issue by therealssj** [kittycash/teller#4]
Create a `skyd` like https://github.com/kittycash/teller/blob/master/cmd/btcd/btcd.go to test skycoin deposits

**Comment by briancaine** [comment]
What's the progress of this? And is it necessary for the IKO?

**Comment by therealssj** [comment]
Not necessary but nice to have for testing.

**Comment by briancaine** [comment]
How long do you think this will take to implement? It'll probably be a copy/paste of the btcd mockup, right? (Or pretty close.)

**Comment by therealssj** [comment]
I am hoping its not hard. MDL created a skyd but I dont like their implementation because its hacky, not sure what issues they faced but there prolly were some thats why its not on my priority list right now.
