### ISSUE TITLE
Integrate with verification service

### ISSUE THREAD

**Issue by therealssj** [kittycash/teller#5]
- [x] Refactor according to latest changes in verification service

Timeframe: Before 1/04

**Comment by therealssj** [comment]
Done.
Waiting for integration with marketplace and bug fixing before closing

**Comment by briancaine** [comment]
Integration / bug fixing where? Is there an issue for it?

**Comment by therealssj** [comment]
No. I consider the integration/bug fixing as a part of this issue only. As I am still testing teller I don’t know if there might be some bugs in my implementations or not

**Comment by briancaine** [comment]
How long will the integration / bug fixing take? Is it waiting on anything?

**Comment by therealssj** [comment]
Nope. 
Its done imo.
I am gonna close this issue once my PR is merged.

**Comment by therealssj** [comment]
fixed: https://github.com/kittycash/teller/pull/1
