### ISSUE TITLE
Telegram Auction Bot

### ISSUE THREAD

**Issue by jdknives** [kittycash/teller#6]
Create a telgram auction Bot that performs the following tasks:

- Tells people who newly join the group to read the pinned message

- Gives updates for people on the remaining time left for the auction.
--> with decreasing time to the end of auction more frequent announcements
--> counts down from 100 to 0 in an interval of 1 sec
--> from 10 to 0, every new bid is starting the 10 to 0 timer again.

- announce the winner and bid that finally won and ask them to PM me (@erichkaestner)

**Comment by therealssj** [comment]
after what time should I delete the welcome msg? 
Like skycoin deletes are `90` seconds

**Comment by jdknives** [comment]
I think 90 seconds is fine.

**Comment by 128-95** [comment]
Moving this to https://github.com/kittycash/telegram-butler
